import Head from 'next/head'
import styles from '../styles/Home.module.css'
import { useEffect,useState } from 'react'
import '@fortawesome/fontawesome-svg-core/styles.css'
import HomeScrean from './Home'
export default function Home() {
  const [windowSize, setWindowSize] = useState({
    width: undefined,
    height: undefined,
  });
  useEffect(() => {
    // only execute all the code below in client side
    if (typeof window !== 'undefined') {
      // Handler to call on window resize
      function handleResize() {
        // Set window width/height to state
        setWindowSize({
          width: window.innerWidth,
          height: window.innerHeight,
        });
      }
    
      // Add event listener
      window.addEventListener("resize", handleResize);
     
      // Call handler right away so state gets updated with initial window size
      handleResize();
    
      // Remove event listener on cleanup
      return () => window.removeEventListener("resize", handleResize);
    }
  }, []); 
  return (
    <div>
      <Head>
        <title>Passato</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css2?family=Inter" rel="stylesheet"/>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      
      
        <HomeScrean/>


      </main>

      <footer className={styles.footer}>
        <div>

        </div>
        
      </footer>
    </div>
  )
}
